# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "BusinessMessage",
    "EngineMessage",
    "ExecutionReport",
    "FIXEvent",
    "FIXPayload",
    "Heartbeat",
    "Logon",
    "NewOrderSingle",
    "OrderCancel",
    "OrderCancelReject",
    "OrderCancelReplace",
    "PyFixClient",
    "PyL3EventExtra",
    "PyLimitOrder",
    "PyMarketEvent",
    "PyMarketEventType",
    "PyMoldClient",
    "PyOrder",
    "PyOrderBook",
    "PyOrderSide",
    "PyOrderType",
    "ReportMessage",
    "ResendRequest",
    "TestRequest",
]

class BusinessMessage:
    @typing.final
    class NewOrderSingle(BusinessMessage):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> NewOrderSingle: ...
        def __new__(cls, _0: NewOrderSingle) -> BusinessMessage.NewOrderSingle: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    @typing.final
    class OrderCancel(BusinessMessage):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> OrderCancel: ...
        def __new__(cls, _0: OrderCancel) -> BusinessMessage.OrderCancel: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    @typing.final
    class OrderCancelReplace(BusinessMessage):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> OrderCancelReplace: ...
        def __new__(cls, _0: OrderCancelReplace) -> BusinessMessage.OrderCancelReplace: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    ...

class EngineMessage:
    @typing.final
    class Logon(EngineMessage):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> Logon: ...
        def __new__(cls, _0: Logon) -> EngineMessage.Logon: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    @typing.final
    class Heartbeat(EngineMessage):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> Heartbeat: ...
        def __new__(cls, _0: Heartbeat) -> EngineMessage.Heartbeat: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    @typing.final
    class TestRequest(EngineMessage):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> TestRequest: ...
        def __new__(cls, _0: TestRequest) -> EngineMessage.TestRequest: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    @typing.final
    class ResendRequest(EngineMessage):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> ResendRequest: ...
        def __new__(cls, _0: ResendRequest) -> EngineMessage.ResendRequest: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    ...

@typing.final
class ExecutionReport:
    r"""
    The Execution Report message is used to:
    • confirm the receipt of an order
    • confirm changes to an existing order
    • confirm cancelation of an existing order
    • relay order status information
    • relay fill information on working orders
    • reject orders
    • report trade busts or other post-trade corrections
    
    `MsgType = 8`
    """
    ...

@typing.final
class FIXEvent:
    @property
    def payload(self) -> FIXPayload: ...
    @payload.setter
    def payload(self, value: FIXPayload) -> None: ...
    @property
    def comp_id(self) -> builtins.str: ...

class FIXPayload:
    @typing.final
    class Engine(FIXPayload):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> EngineMessage: ...
        def __new__(cls, _0: EngineMessage) -> FIXPayload.Engine: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    @typing.final
    class Business(FIXPayload):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> BusinessMessage: ...
        def __new__(cls, _0: BusinessMessage) -> FIXPayload.Business: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    @typing.final
    class Report(FIXPayload):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> ReportMessage: ...
        def __new__(cls, _0: ReportMessage) -> FIXPayload.Report: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    ...

@typing.final
class Heartbeat:
    r"""
    During periods of message inactivity, FIX applications will generate Heartbeat messages at regular time intervals.
    
    `MsgType = 0`
    """
    ...

@typing.final
class Logon:
    r"""
    The logon message authenticates a user establishing a connection to a remote system.
    
    `MsgType = A`
    """
    ...

@typing.final
class NewOrderSingle:
    r"""
    New Order Single is used to send a regular or Block order.
    
    `MsgType = D`
    """
    ...

@typing.final
class OrderCancel:
    r"""
    The Order Cancel Request message is used to cancel a regular or multi-leg order.
    
    `MsgType = F`
    """
    ...

@typing.final
class OrderCancelReject:
    r"""
    An Order Cancel Reject message is returned by the exchange in the event of an invalid cancel or modify request.
    
    `MsgType = 9`
    """
    ...

@typing.final
class OrderCancelReplace:
    r"""
    The Order Cancel Replace Request message is used to modify a regular order.
    
    `MsgType = G`
    """
    ...

@typing.final
class PyFixClient:
    @staticmethod
    def start(server_addr: builtins.str, comp_id: builtins.str, target_comp_id: builtins.str) -> PyFixClient: ...
    def next_report(self) -> typing.Optional[FIXEvent]: ...
    def send_message(self, order: PyOrder) -> None: ...
    def send_generic_message(self) -> None: ...

@typing.final
class PyL3EventExtra:
    @staticmethod
    def cancel(old_price: builtins.int, old_qty: builtins.int) -> PyL3EventExtra: ...
    @staticmethod
    def none() -> PyL3EventExtra: ...

@typing.final
class PyLimitOrder:
    def __new__(cls, order: PyOrder) -> PyLimitOrder: ...

@typing.final
class PyMarketEvent:
    @property
    def timestamp(self) -> builtins.int: ...
    @property
    def kind(self) -> PyMarketEventType: ...
    def __new__(cls, timestamp: builtins.int, kind: PyMarketEventType) -> PyMarketEvent: ...

@typing.final
class PyMarketEventType:
    @staticmethod
    def l3(event: PyOrder, extra: PyL3EventExtra) -> PyMarketEventType: ...
    @staticmethod
    def trade(price: builtins.int, quantity: builtins.int, aggressor_side: PyOrderSide, maker_id: builtins.int) -> PyMarketEventType: ...
    def is_trade(self) -> builtins.bool: ...
    def trade_price(self) -> typing.Optional[builtins.int]: ...
    def trade_quantity(self) -> typing.Optional[builtins.int]: ...

@typing.final
class PyMoldClient:
    @staticmethod
    def start() -> PyMoldClient: ...
    def next_event(self) -> typing.Optional[PyMarketEvent]: ...

@typing.final
class PyOrder:
    def __new__(cls, order_id: builtins.int, side: PyOrderSide, timestamp: builtins.int, kind: PyOrderType) -> PyOrder: ...

@typing.final
class PyOrderBook:
    r"""
    A stripped down version of the OrderBook. Directly manages its state
    via MarketEvents instead of handling matching logic, trade execution, etc.
    """
    def __new__(cls) -> PyOrderBook: ...
    def process_event(self, event: PyMarketEvent) -> None:
        r"""
        Accepts a market event and updates the state of the book
        """
    def best_bid(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the best bidding price or None if there are no bids
        """
    def best_bid_and_size(self) -> typing.Optional[tuple[builtins.int, builtins.int]]:
        r"""
        Returns a tuple of (best_bid_price,qty) or None if there are no bids
        """
    def best_ask(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the best asking price or None if there are no bids
        """
    def best_ask_and_size(self) -> typing.Optional[tuple[builtins.int, builtins.int]]:
        r"""
        Returns a tuple of (best_ask_price,qty) or None if there are no bids
        """
    def mid_price(self) -> typing.Optional[builtins.float]:
        r"""
        Returns an average of the best asking and bidding prices or None if there are no bids or no orders
        """
    def spread(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the difference between the best asking and bidding prices or None if there are no bids or no orders
        """
    def get_level(self, price: builtins.int, side: PyOrderSide) -> builtins.int:
        r"""
        Returns the quantity of a given price level on the specified side
        """
    def get_top_levels(self, side: PyOrderSide, n: builtins.int) -> builtins.list[tuple[builtins.int, builtins.int]]:
        r"""
        Returns the quantities of the top n price levels on the specified side
        """

@typing.final
class PyOrderType:
    @staticmethod
    def limit(qty: builtins.int, price: builtins.int) -> PyOrderType: ...
    @staticmethod
    def market(qty: builtins.int) -> PyOrderType: ...
    @staticmethod
    def update(old_id: builtins.int, qty: builtins.int, price: builtins.int) -> PyOrderType: ...
    @staticmethod
    def cancel(old_id: builtins.int) -> PyOrderType: ...

class ReportMessage:
    @typing.final
    class ExecutionReport(ReportMessage):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> ExecutionReport: ...
        def __new__(cls, _0: ExecutionReport) -> ReportMessage.ExecutionReport: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    @typing.final
    class OrderCancelReject(ReportMessage):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> OrderCancelReject: ...
        def __new__(cls, _0: OrderCancelReject) -> ReportMessage.OrderCancelReject: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int) -> typing.Any: ...
    
    ...

@typing.final
class ResendRequest:
    r"""
    The resend request is sent by the receiving application to initiate the retransmission of messages.
    
    `MsgType = 2`
    """
    ...

@typing.final
class TestRequest:
    r"""
    The test request message forces a heartbeat from the opposing application.
    
    `MsgType = 1`
    """
    ...

@typing.final
class PyOrderSide(enum.Enum):
    Bid = ...
    Ask = ...

